### ISSUE TITLE
button shows but cannot download videos

### ISSUE THREAD

**Issue by jake2townz** [Neet-Nestor/Telegram-Media-Downloader#12]
a button displays when i'm playing a video, but nothing happens when i click it. it still works fine when downloading photos.

**Comment by Neet-Nestor** [comment]
Thanks for using it and report for this issue. For video, once you clicked the button it will start the downloading **in background**, and only triggers the actual save once the download is finished. So please wait carefully after clicking the button. This is due to the nature of stream format of Telegram videos.

You can verify the download has been started by open browser's tool -> console, and there should be text printed indicating the current download progress. Please re-open this issue if you cannot find it.

There's a plan to add a download progress UI to make it more intuitive (since it's clearly causing a lot of confusion), but unfortunately I personally don't have plenty of time working on it. It may be added in a later version.

**Comment by jake2townz** [comment]
There is no download progress, unfortunately. Here's a snapshot of my console while using the script.
[console-export-2023-5-25_9-56-51.txt](https://github.com/Neet-Nestor/Telegram-Media-Downloader/files/11560473/console-export-2023-5-25_9-56-51.txt)
