### ISSUE TITLE
I can't download an audio

### ISSUE THREAD

**Issue by kreont007** [Neet-Nestor/Telegram-Media-Downloader#50]
Hi 
I have been downloading audio from the channel couple of weeks ago, but i can not do it now. There is not even any button "download"
![2024-01-22_14-40-24](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/157370476/ff0d5561-8a06-4b67-8085-1a76c413bd76)

**Comment by Neet-Nestor** [comment]
Thanks for raising this into my attention. I will have a look later. In the meanwhile, feel free to downgrade to previous versions to see if it's working.

**Comment by Neet-Nestor** [comment]
Hi @kreont007 , I checked it and realized that it's just the button icon issue. Due to a recent icon change in telegram /k/ , the download button shows as a "remove user" button on the tab bar but it actually does the download. I will release an updated version to update it.

<img width="217" alt="Screenshot 2024-01-30 at 10 27 30 PM" src="https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/23090573/10004f6a-6802-4b19-aaa3-96e0c40c1aa0">

**Comment by Neet-Nestor** [comment]
Released in v1.103 (04c5aa3ade765bc295f1abd9bd81bff304d6df9e)

**Comment by kreont007** [comment]
> Released in v1.103 ([04c5aa3](https://github.com/Neet-Nestor/Telegram-Media-Downloader/commit/04c5aa3ade765bc295f1abd9bd81bff304d6df9e))

Hi dear author!

I have installed new version, but it is the same) I do not see new button for downloading...
![2024-01-31_15-27-39](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/157370476/aa972c7d-46ce-4fe9-962b-0932e4576909)
![2024-01-31_15-28-00](https://github.com/Neet-Nestor/Telegram-Media-Downloader/assets/157370476/cb40416d-42b8-4913-b116-62a8e2abe4f3)

**Comment by Neet-Nestor** [comment]
Also make sure you are using the newest version.
https://greasyfork.org/zh-CN/scripts/446342-telegram-media-downloader?version=1320143

It was my mistake that I published a wrong code as v1.103 so I had to publish two different v1.103 on Greasyfork. Please make sure you installed the latest one.

**Comment by kreont007** [comment]
I have reinstalled and it works now!
Thank you so much for such a valuable product!!!!!!!

**Comment by Neet-Nestor** [comment]
You're welcome :)
