### ISSUE TITLE
since yesterday, it has not downloaded large videos ~ 1 gb

### ISSUE THREAD

**Issue by Chupacabrara** [Neet-Nestor/Telegram-Media-Downloader#91]
since yesterday, it has not downloaded large videos ~ 1 gb, the speed is interrupted by about 18-20%, it is impossible to continue downloading

**Comment by Chupacabrara** [comment]
upd: downloads large videos is working if don't turn off video playback

**Comment by Neet-Nestor** [comment]
> upd: downloads large videos is working if don't turn off video playback

Thank you for reporting this! This really affirms my assumption. As the script is simply loading the video content using the same methods as the webapp, my guess is that the server will close the connection if the webapp playback is closed and inactivate for a while.

From the script side I don't know a good approach to bypass it, so I will just recommend you keep the playback open for large video files.

I will close this due to the reason above, but feel free to reopen this if you have discovered anything new.
